### ISSUE TITLE
Footer to include link to Etherscan and Github

### ISSUE THREAD

**Issue by marsrobertson** [kleros/binary-arbitrable-proxy-contract#5]
Github - to encourage checking the code, reporting issues
Etherscan - to encourage viewing the smart contract

Similar footer to be implemented in other Kleros online-real-estate (DApps)

**Comment by ferittuncer** [comment]
This is the contract repository, but it's OK : )

For future issues please report here: https://github.com/kleros/binary-arbitrable-proxy

**Comment by marsrobertson** [comment]
Ouch!

As an owner you can move the issue.

It also highlights the need for links in repo - link to contract, link to website

**Comment by ferittuncer** [comment]
Also to Reddit and Slack...

**Comment by ferittuncer** [comment]
Fixed.
